name: Build test apk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branch
  push:
    branches: [ testing ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Generate Release APK
        run: ./gradlew assembleRelease      
      
      - name: Generate Debug APK
        run: ./gradlew assembleDebug
      
      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app_release
        with:
          releaseDirectory: app/phone/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Sign Debug APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app_debug
        with:
          releaseDirectory: app/phone/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - name: Set tag
        id: tag
        run: echo "tag=$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Rename Release APK
        working-directory: app/phone/build/outputs/apk/release/
        run: mv phone-arm64-v8a-release-unsigned-signed.apk testing-release-arm64-v8a-${{ steps.tag.outputs.tag }}.apk

      - name: Rename Debug APK
        working-directory: app/phone/build/outputs/apk/debug/
        run: mv phone-arm64-v8a-debug-signed.apk testing-debug-arm64-v8a-${{ steps.tag.outputs.tag }}.apk

      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: findroid-apk
          path: |
            app/phone/build/outputs/apk/release/testing-release-arm64-v8a-${{ steps.tag.outputs.tag }}.apk
            app/phone/build/outputs/apk/debug/testing-debug-arm64-v8a-${{ steps.tag.outputs.tag }}.apk
       
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.tag.outputs.tag }}
          prerelease: false
          title: "Testing Build"
          files: |
            app/phone/build/outputs/apk/release/testing-release-arm64-v8a-${{ steps.tag.outputs.tag }}.apk
            app/phone/build/outputs/apk/debug/testing-debug-arm64-v8a-${{ steps.tag.outputs.tag }}.apk