# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - "develop"

jobs:
  synchronise-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "testing"
          fetch-depth: 0
      - uses: pr-mpt/actions-merge-branch@v0
        with:
          from: "origin/develop"
