name: Sync Fork

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: jarnedemeulemeester
          base: testing2
          head: main
